backup_settings:
  platform:
    windows:
      backup_name: dotborn_windows_backup
      output_dir: "%USERPROFILE%"
      flags:
        include_private_keys: false
        compress: false
        output_tarball: false
        encrypt_backup: false
      targets:
        browser_data:
        credentials:
          - "%USERPROFILE%/.ssh/id_rsa"
        dotfiles:
          - "%USERPROFILE%/.bashrc"
          - "%USERPROFILE%/.wslconfig"
          - "%USERPROFILE%/.gitconfig"
          - "%USERPROFILE%/.gitignore_global"
          - "%USERPROFILE%/.ssh/config"
        configs:
          - "%APPDATA%/Code/User/settings.json"
          - "%USERPROFILE%/.vscode/"
        sysfiles:
          - None
        usr_dirs:
          - None
    linux:
      backup_name: dotborn_linux_backup
      output_dir: "~"
      flags:
        include_private_keys: false
        compress: true
        output_tarball: true
        encrypt_backup: true
      targets:
        browser_data:
          - ~/.mozilla/firefox
        credentials:
          - ~/.ssh/id_rsa
        dotfiles:
          - ~/.bashrc
          - ~/.gitconfig
          - ~/.tmux.conf
          - ~/.zshrc
        configs:
          - ~/.config/bat
          - ~/.config/htop
          - ~/.config/nvim
          - ~/.config/neofetch
          - ~/.gh
          - ~/.oh-my-zsh/themes/mimir.zsh-theme
        sysfiles:
          - /etc/ssh/ssh_config
          - /etc/ssh/sshd_config
        usr_dirs:
          - None