# Dotborn - System Setup and Dotfile Installation

## GENERAL SETTINGS
system_settings:
  username: logank
  home_dir: /home/logank
  backup_dir: /home/logank/dotborn_backups # TODO: Make this and home_dir easier to work with
  encrypt_backup: false
  include_private_keys: false
  logging:
    level: info
    log_to_file: true
    rich_output: true
    log_path: ./dotborn.log
  flags:
    dry_run: true
    interactive: true
    quiet: false
    allow_sudo: true
## BACKUP SETTINGS
backup_settings:
  compress: false
  output_tarball: false
  tarball_name: dotborn_backup.tar.gz
  backup_targets:
    windows:
      enabled: false
      paths:
        credentials:
        dotfiles:
        config_dirs:
        sys_dirs:
        #usr_dirs: optional user-defined directories
    linux:
      enabled: true
      paths:
        credentials:
        dotfiles:
          - ~/.bashrc
          - ~/.gitconfig
          - ~/.tmux.conf
          - ~/.zshrc
        config_dirs:
          - ~/.config/bat
          - ~/.config/htop
          - ~/.config/nvim
          - ~/.config/neofetch
          - ~/.config/ranger
          - ~/.gh
          - ~/.oh-my-zsh/themes/mimir.zsh-theme
        sys_dirs:
          - /etc/ssh/ssh_config
          - /etc/ssh/sshd_config
        #usr_dirs: optional user-defined directories

## INSTALL SETTINGS
install_settings:
  method: copy # 'copy'|'symlink' (bare report support could be added?)
  installed_by:
    apt:
      - asciinema
      - bat
      - bpytop
      - build-essential
      - cmatrix
      - curl
      - debianutils
      - ffmpeg
      - figlet
      - git
      - glances
      - gnupg
      - htop
      - iftop
      - lshw
      - lsof
      - lynx
      - neofetch
      - neovim
      - net-tools
      - nmap
      - p7zip-full
      - python3-pip
      - python3-venv
      - ranger
      - tmux
      - toilet
      - unzip
      - vlc
      - wget
      - zip
      - zsh
    cargo:
      - dua-cli
      - watchexec-cli
      - bottom
      - ytop
      - xplr
      - starship
    script:
      - oh-my-zsh:
          install: curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
          description: zsh framework
      - nerd_fonts:
          install: # TODO: Write custom script
          fonts:
            - Mononoki
            - Hack
            - JetBrainsMono
          description: Patched fonts for glyph-friendly terminals
      - gh:
          install: #TODO: Write custom script
          description: GitHub CLI
      - fzf:
          install: git clone https://github.com/junegunn/fzf.git ~/.fzf && ~/.fzf/install --all
          description: Command-line fuzzy finder
      - usr_scripts: [] # path/to/custom/script(s)
  dotfile_options:
    method: copy
    overwrite_existing: true
  post_install:
    show_tips: true
    reshell: true
    run_script: postinstall.sh
